// <auto-generated />
namespace SurfergraphyApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class surfergraphy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(surfergraphy));
        
        string IMigrationMetadata.Id
        {
            get { return "201802220807304_surfergraphy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
