// <auto-generated />
namespace SurfergraphyApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init_5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_5));
        
        string IMigrationMetadata.Id
        {
            get { return "201802280743140_init_5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
